#!/usr/bin/env node
/**
 * The blog, edited from this repo.
 *
 * ## Why this exists
 *
 * The blog is WordPress, on the same Bluehost account as everything else, and
 * the obvious way to write a post is to log in and type it into wp-admin. This
 * is the other way: posts live here as Markdown files under `content/blog/`,
 * in git, reviewed like any other change, and pushed up over the REST API.
 *
 * The point is not that typing into WordPress is hard. It is that a post
 * written here has a history — you can see what it said last month, and why it
 * changed — and that it can be drafted by someone who does not have, and should
 * not need, a login.
 *
 * ## What it will not do
 *
 * It will not publish. `push` sends everything as a draft unless you pass
 * `--allow-publish`, and even then only if the file itself says
 * `status: publish`. Two locks, because publishing is the one action here that
 * is public, immediate and awkward to take back — and because a tool that can
 * publish by accident eventually will.
 *
 * `trash` moves a post to the WordPress trash. It never force-deletes; the bin
 * is emptied from wp-admin by a person.
 *
 * ## Credentials
 *
 * `WP_USER` and `WP_APP_PASSWORD` from `.env.local`, which `.gitignore` covers.
 * The password is an Application Password — generated by WordPress, scoped to
 * the API, revocable from Users → Profile without touching the real account
 * password. Nothing here prints it.
 *
 * ## Usage
 *
 *   node scripts/blog.mjs list
 *   node scripts/blog.mjs pull 12            → content/blog/<slug>.md
 *   node scripts/blog.mjs push content/blog/my-post.md
 *   node scripts/blog.mjs push content/blog/my-post.md --allow-publish
 *   node scripts/blog.mjs trash 12
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CONTENT = join(ROOT, 'content', 'blog');
const API = 'https://thallodigital.com/blog/wp-json/wp/v2';

/* ── Credentials ─────────────────────────────────────────────────────────── */

function env() {
  const file = join(ROOT, '.env.local');
  if (!existsSync(file)) die('.env.local not found. Copy .env.example and fill in WP_USER and WP_APP_PASSWORD.');

  const vars = Object.fromEntries(
    readFileSync(file, 'utf8')
      .split('\n')
      .filter((l) => l.trim() && !l.trim().startsWith('#'))
      .map((l) => {
        const i = l.indexOf('=');
        return i < 0 ? ['', ''] : [l.slice(0, i).trim(), l.slice(i + 1).trim()];
      })
  );

  if (!vars.WP_USER || !vars.WP_APP_PASSWORD) {
    die('WP_USER or WP_APP_PASSWORD is empty in .env.local.\nGet an Application Password from /blog/wp-admin/profile.php.');
  }
  return vars;
}

function auth() {
  const { WP_USER, WP_APP_PASSWORD } = env();
  return 'Basic ' + Buffer.from(`${WP_USER}:${WP_APP_PASSWORD}`).toString('base64');
}

/* ── The API ─────────────────────────────────────────────────────────────── */

/**
 * @param attempt Retries are for the connection, never for the request.
 *
 * A `POST` that reached WordPress and then timed out on the way back may well
 * have created the post; retrying it would create a second one. So only a
 * failure to connect at all is retried — at that point nothing was sent.
 */
async function api(path, init = {}, attempt = 1) {
  let res;
  try {
    res = await fetch(`${API}${path}`, {
      ...init,
      headers: { Authorization: auth(), 'Content-Type': 'application/json', ...(init.headers || {}) },
    });
  } catch (e) {
    const connect = e?.cause?.code === 'UND_ERR_CONNECT_TIMEOUT' || e?.cause?.code === 'ENOTFOUND';
    if (connect && attempt < 4) {
      console.error(`  … could not reach the server, retrying (${attempt}/3)`);
      await new Promise((r) => setTimeout(r, 2000 * attempt));
      return api(path, init, attempt + 1);
    }
    die(`Could not reach ${API}.\n${e?.cause?.code || e.message}\nCheck the connection and try again.`);
  }

  const text = await res.text();
  let body;
  try {
    body = JSON.parse(text);
  } catch {
    body = text;
  }

  if (!res.ok) {
    /* WordPress puts something useful in `message`; a security layer in front
       of it usually does not, so the raw body is worth showing when there is
       no structured error to read. */
    const detail = body && body.message ? body.message : String(body).slice(0, 400);
    die(`${init.method || 'GET'} ${path} → ${res.status}\n${detail}`);
  }

  return body;
}

/* ── Front matter ────────────────────────────────────────────────────────── */

/**
 * A deliberately small parser: `key: value` lines between `---` fences, values
 * taken literally. No YAML library, because the only shapes here are strings,
 * one number and one comma-separated list, and a full YAML parser would invite
 * files this tool then has to keep understanding.
 */
function parse(raw) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) die('No front matter. A post starts with a --- block; see the example in content/blog/.');

  const meta = {};
  for (const line of m[1].split('\n')) {
    const i = line.indexOf(':');
    if (i < 0) continue;
    meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return { meta, body: m[2] };
}

function serialise(meta, body) {
  const lines = Object.entries(meta)
    .filter(([, v]) => v !== undefined && v !== '')
    .map(([k, v]) => `${k}: ${v}`);
  return `---\n${lines.join('\n')}\n---\n\n${body}`;
}

/* ── Commands ────────────────────────────────────────────────────────────── */

async function list() {
  const posts = await api('/posts?per_page=50&status=any&context=edit&_fields=id,slug,status,date,title');
  if (!posts.length) return console.log('No posts.');

  for (const p of posts) {
    const date = p.date.slice(0, 10);
    console.log(`${String(p.id).padStart(4)}  ${p.status.padEnd(8)} ${date}  ${p.title.raw || p.title.rendered}`);
  }
}

async function pull(id) {
  if (!id) die('Usage: pull <id>');
  const p = await api(`/posts/${id}?context=edit`);

  mkdirSync(CONTENT, { recursive: true });
  const file = join(CONTENT, `${p.slug || 'post-' + p.id}.md`);

  /* The body comes down as HTML and is written as HTML. Converting it back to
     Markdown would be a guess, and a lossy one — this file is for editing an
     existing post, not for pretending it was ever Markdown. New posts written
     from scratch here are Markdown and are converted on the way up. */
  writeFileSync(
    file,
    serialise(
      {
        wpId: p.id,
        title: p.title.raw,
        slug: p.slug,
        status: p.status,
        excerpt: p.excerpt.raw.replace(/\s+/g, ' ').trim(),
        format: 'html',
      },
      p.content.raw
    )
  );

  console.log(`→ ${file}`);
}

async function push(file, allowPublish) {
  if (!file) die('Usage: push <file.md> [--allow-publish]');
  const path = resolve(file);
  const { meta, body } = parse(readFileSync(path, 'utf8'));

  if (!meta.title) die('Front matter needs a title.');

  /* Two locks on publishing, and this is the second: the file has to ask for
     it AND the command line has to allow it. Anything else becomes a draft,
     including a file that says `publish` and was pushed without the flag. */
  let status = meta.status || 'draft';
  if (status === 'publish' && !allowPublish) {
    console.log('! file says status: publish, but --allow-publish was not given — pushing as a draft');
    status = 'draft';
  }

  const content = meta.format === 'html' ? body : marked.parse(body, { mangle: false, headerIds: false });

  const payload = { title: meta.title, content, status };
  if (meta.slug) payload.slug = meta.slug;
  if (meta.excerpt) payload.excerpt = meta.excerpt;

  const existing = meta.wpId && Number(meta.wpId);
  const result = existing
    ? await api(`/posts/${existing}`, { method: 'POST', body: JSON.stringify(payload) })
    : await api('/posts', { method: 'POST', body: JSON.stringify(payload) });

  if (!existing) {
    /* Written back so the next push updates this post instead of creating a
       second copy of it. */
    writeFileSync(path, serialise({ wpId: result.id, ...meta }, body));
    console.log(`created #${result.id} · wpId written back to ${file}`);
  } else {
    console.log(`updated #${result.id}`);
  }

  console.log(`status: ${result.status}\n${result.link}`);
  if (result.status !== 'publish') {
    console.log('Draft — nothing is public until you publish it from wp-admin.');
  }
}

async function trash(id) {
  if (!id) die('Usage: trash <id>');
  /* No `force=true`. This moves the post to the WordPress trash, where it can
     be restored; emptying the bin is a decision for a person in wp-admin. */
  const r = await api(`/posts/${id}`, { method: 'DELETE' });
  console.log(`#${id} → ${r.status || 'trash'} (restorable from wp-admin)`);
}

/* ── Entry ───────────────────────────────────────────────────────────────── */

function die(message) {
  console.error(message);
  process.exit(1);
}

const [command, arg] = process.argv.slice(2);
const allowPublish = process.argv.includes('--allow-publish');

const commands = {
  list: () => list(),
  pull: () => pull(arg),
  push: () => push(arg, allowPublish),
  trash: () => trash(arg),
};

if (!commands[command]) {
  die('Commands: list · pull <id> · push <file> [--allow-publish] · trash <id>');
}

await commands[command]();
