#!/usr/bin/env node
/**
 * The blog, edited from this repo.
 *
 * ## Why this exists
 *
 * The blog is WordPress, on the same Bluehost account as everything else, and
 * the obvious way to write a post is to log in and type it into wp-admin. This
 * is the other way: posts live here as Markdown files under `content/blog/`,
 * in git, reviewed like any other change, and pushed up over the REST API.
 *
 * The point is not that typing into WordPress is hard. It is that a post
 * written here has a history — you can see what it said last month, and why it
 * changed — and that it can be drafted by someone who does not have, and should
 * not need, a login.
 *
 * ## What it will not do
 *
 * It will not publish. `push` sends everything as a draft unless you pass
 * `--allow-publish`, and even then only if the file itself says
 * `status: publish`. Two locks, because publishing is the one action here that
 * is public, immediate and awkward to take back — and because a tool that can
 * publish by accident eventually will.
 *
 * `trash` moves a post to the WordPress trash. It never force-deletes; the bin
 * is emptied from wp-admin by a person.
 *
 * ## Credentials
 *
 * `WP_USER` and `WP_APP_PASSWORD` from `.env.local`, which `.gitignore` covers.
 * The password is an Application Password — generated by WordPress, scoped to
 * the API, revocable from Users → Profile without touching the real account
 * password. Nothing here prints it.
 *
 * ## Usage
 *
 *   node scripts/blog.mjs list
 *   node scripts/blog.mjs pull 12            → content/blog/<slug>.md
 *   node scripts/blog.mjs push content/blog/my-post.md
 *   node scripts/blog.mjs push content/blog/my-post.md --allow-publish
 *   node scripts/blog.mjs trash 12
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CONTENT = join(ROOT, 'content', 'blog');
const API = 'https://thallodigital.com/blog/wp-json/wp/v2';

/* ── Credentials ─────────────────────────────────────────────────────────── */

function env() {
  const file = join(ROOT, '.env.local');
  if (!existsSync(file)) die('.env.local not found. Copy .env.example and fill in WP_USER and WP_APP_PASSWORD.');

  const vars = Object.fromEntries(
    readFileSync(file, 'utf8')
      .split('\n')
      .filter((l) => l.trim() && !l.trim().startsWith('#'))
      .map((l) => {
        const i = l.indexOf('=');
        return i < 0 ? ['', ''] : [l.slice(0, i).trim(), l.slice(i + 1).trim()];
      })
  );

  if (!vars.WP_USER || !vars.WP_APP_PASSWORD) {
    die('WP_USER or WP_APP_PASSWORD is empty in .env.local.\nGet an Application Password from /blog/wp-admin/profile.php.');
  }
  return vars;
}

function auth() {
  const { WP_USER, WP_APP_PASSWORD } = env();
  return 'Basic ' + Buffer.from(`${WP_USER}:${WP_APP_PASSWORD}`).toString('base64');
}

/* ── The API ─────────────────────────────────────────────────────────────── */

/**
 * @param attempt Retries are for the connection, never for the request.
 *
 * A `POST` that reached WordPress and then timed out on the way back may well
 * have created the post; retrying it would create a second one. So only a
 * failure to connect at all is retried — at that point nothing was sent.
 */
async function api(path, init = {}, attempt = 1) {
  let res;
  try {
    res = await fetch(`${API}${path}`, {
      ...init,
      headers: { Authorization: auth(), 'Content-Type': 'application/json', ...(init.headers || {}) },
    });
  } catch (e) {
    const connect = e?.cause?.code === 'UND_ERR_CONNECT_TIMEOUT' || e?.cause?.code === 'ENOTFOUND';
    if (connect && attempt < 4) {
      console.error(`  … could not reach the server, retrying (${attempt}/3)`);
      await new Promise((r) => setTimeout(r, 2000 * attempt));
      return api(path, init, attempt + 1);
    }
    die(`Could not reach ${API}.\n${e?.cause?.code || e.message}\nCheck the connection and try again.`);
  }

  const text = await res.text();
  let body;
  try {
    body = JSON.parse(text);
  } catch {
    body = text;
  }

  if (!res.ok) {
    /* WordPress puts something useful in `message`; a security layer in front
       of it usually does not, so the raw body is worth showing when there is
       no structured error to read. */
    const detail = body && body.message ? body.message : String(body).slice(0, 400);
    die(`${init.method || 'GET'} ${path} → ${res.status}\n${detail}`);
  }

  return body;
}

/* ── Front matter ────────────────────────────────────────────────────────── */

/**
 * A deliberately small parser: `key: value` lines between `---` fences, values
 * taken literally. No YAML library, because the only shapes here are strings,
 * one number and one comma-separated list, and a full YAML parser would invite
 * files this tool then has to keep understanding.
 */
function parse(raw) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) die('No front matter. A post starts with a --- block; see the example in content/blog/.');

  const meta = {};
  for (const line of m[1].split('\n')) {
    const i = line.indexOf(':');
    if (i < 0) continue;
    meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return { meta, body: m[2] };
}

function serialise(meta, body) {
  const lines = Object.entries(meta)
    .filter(([, v]) => v !== undefined && v !== '')
    .map(([k, v]) => `${k}: ${v}`);
  return `---\n${lines.join('\n')}\n---\n\n${body}`;
}

/* ── Markdown → Gutenberg ────────────────────────────────────────────────── */

/**
 * Splits rendered HTML into its top-level pieces.
 *
 * A depth counter rather than a regex. Regexes cannot count, and a list
 * containing a nested list is exactly the case where one stops being able to
 * tell which `</ul>` ends the outer element.
 */
function topLevel(html) {
  const out = [];
  const tag = /<(\/?)([a-z][a-z0-9]*)\b[^>]*?(\/?)>|<!--[\s\S]*?-->/gi;

  let depth = 0;
  let start = 0;
  let m;

  while ((m = tag.exec(html))) {
    const [raw, closing, name, selfClosed] = m;

    // A comment or a void element at depth 0 is a piece all by itself.
    if (!name || selfClosed || /^(br|hr|img|input|source)$/i.test(name || '')) {
      if (depth === 0) {
        const before = html.slice(start, m.index).trim();
        if (before) out.push(before);
        out.push(raw);
        start = m.index + raw.length;
      }
      continue;
    }

    if (closing) {
      depth--;
      if (depth === 0) {
        out.push(html.slice(start, m.index + raw.length).trim());
        start = m.index + raw.length;
      }
    } else {
      if (depth === 0) {
        const before = html.slice(start, m.index).trim();
        if (before) out.push(before);
        start = m.index;
      }
      depth++;
    }
  }

  const tail = html.slice(start).trim();
  if (tail) out.push(tail);

  return out.filter(Boolean);
}

/**
 * Wraps plain HTML in the block delimiters WordPress stores posts as.
 *
 * Without this a pushed post arrives as one undifferentiated lump — it renders
 * correctly, but in the editor it is a single Classic block, so the patterns,
 * the block settings and every normal editing gesture stop working on it. The
 * point of writing here was never to make the post harder to edit there.
 *
 * Anything already in block markup is passed through untouched, which is what
 * lets a Markdown file drop a pattern — a callout, the scanner panel — into
 * the middle of otherwise ordinary prose.
 */
function toBlocks(html) {
  return regions(html)
    .flatMap((region) => (region.passthrough ? [region.text] : wrap(region.text)))
    .join('\n\n');
}

/**
 * Separates spans that are already block markup from spans that are plain HTML.
 *
 * A block is its opening delimiter, its markup, and its closing delimiter, and
 * those three have to survive as one piece. Splitting on HTML tags alone tore
 * them apart — the `<!-- wp:group -->` comment came out as one chunk and the
 * `<div>` it introduces as another, so the div got wrapped as raw HTML and the
 * pattern arrived in the editor as an uneditable lump. Nesting is counted,
 * because a group contains blocks and the first `<!-- /wp: -->` encountered is
 * usually not the one that closes it.
 */
function regions(html) {
  const OPEN = /<!--\s+wp:([a-z][a-z0-9-]*(?:\/[a-z0-9-]+)?)(?:\s+\{.*?\})?\s+(\/)?-->/g;
  const out = [];
  let cursor = 0;
  let m;

  while ((m = OPEN.exec(html))) {
    if (m.index < cursor) continue;

    const plain = html.slice(cursor, m.index).trim();
    if (plain) out.push({ text: plain, passthrough: false });

    // A self-closing block — `<!-- wp:separator /-->` — is the whole region.
    if (m[2]) {
      out.push({ text: m[0], passthrough: true });
      cursor = m.index + m[0].length;
      OPEN.lastIndex = cursor;
      continue;
    }

    const name = m[1];
    const delim = new RegExp(`<!--\\s+(/)?wp:${name}(?:\\s+\\{.*?\\})?\\s+/?-->`, 'g');
    delim.lastIndex = m.index + m[0].length;

    let depth = 1;
    let end = -1;
    let d;
    while ((d = delim.exec(html))) {
      depth += d[1] ? -1 : 1;
      if (depth === 0) {
        end = d.index + d[0].length;
        break;
      }
    }

    /* An unclosed block is left to WordPress rather than guessed at: it will
       flag it in the editor, which is more useful than this silently
       swallowing the rest of the post into one region. */
    if (end === -1) end = m.index + m[0].length;

    out.push({ text: html.slice(m.index, end).trim(), passthrough: true });
    cursor = end;
    OPEN.lastIndex = cursor;
  }

  const tail = html.slice(cursor).trim();
  if (tail) out.push({ text: tail, passthrough: false });

  return out;
}

/** Wraps a span of plain HTML, element by element, in block delimiters. */
function wrap(html) {
  return topLevel(html)
    .map((chunk) => {
      if (chunk.startsWith('<!--')) return chunk;
      const tag = (chunk.match(/^<([a-z][a-z0-9]*)/i) || [])[1]?.toLowerCase();

      switch (tag) {
        case 'h1':
        case 'h2':
        case 'h3':
        case 'h4':
        case 'h5':
        case 'h6': {
          const level = Number(tag[1]);
          const attrs = level === 2 ? '' : ` {"level":${level}}`;
          const withClass = chunk.replace(/^<h(\d)/, '<h$1 class="wp-block-heading"');
          return `<!-- wp:heading${attrs} -->\n${withClass}\n<!-- /wp:heading -->`;
        }
        case 'p':
          return `<!-- wp:paragraph -->\n${chunk}\n<!-- /wp:paragraph -->`;
        case 'ul':
        case 'ol': {
          const ordered = tag === 'ol';
          const items = chunk.replace(
            /<li>([\s\S]*?)<\/li>/g,
            (_, inner) => `<!-- wp:list-item -->\n<li>${inner}</li>\n<!-- /wp:list-item -->`
          );
          const listed = items.replace(new RegExp(`^<${tag}>`), `<${tag} class="wp-block-list">`);
          return `<!-- wp:list${ordered ? ' {"ordered":true}' : ''} -->\n${listed}\n<!-- /wp:list -->`;
        }
        case 'blockquote':
          return `<!-- wp:quote -->\n${chunk.replace('<blockquote>', '<blockquote class="wp-block-quote">')}\n<!-- /wp:quote -->`;
        case 'pre':
          return `<!-- wp:code -->\n${chunk.replace('<pre>', '<pre class="wp-block-code">')}\n<!-- /wp:code -->`;
        case 'hr':
          return `<!-- wp:separator -->\n<hr class="wp-block-separator has-alpha-channel-opacity"/>\n<!-- /wp:separator -->`;
        case 'table':
          return `<!-- wp:table -->\n<figure class="wp-block-table">${chunk}</figure>\n<!-- /wp:table -->`;
        case 'figure':
        case 'img':
          return `<!-- wp:image -->\n${chunk}\n<!-- /wp:image -->`;
        default:
          /* Unknown markup goes up as an HTML block rather than being dropped
             or guessed at. It renders, and the editor says plainly that it is
             raw HTML rather than pretending to understand it. */
          return `<!-- wp:html -->\n${chunk}\n<!-- /wp:html -->`;
      }
    })
    .join('\n\n');
}

/* ── Commands ────────────────────────────────────────────────────────────── */

async function list() {
  const posts = await api('/posts?per_page=50&status=any&context=edit&_fields=id,slug,status,date,title');
  if (!posts.length) return console.log('No posts.');

  for (const p of posts) {
    const date = p.date.slice(0, 10);
    console.log(`${String(p.id).padStart(4)}  ${p.status.padEnd(8)} ${date}  ${p.title.raw || p.title.rendered}`);
  }
}

async function pull(id, dest) {
  if (!id) die('Usage: pull <id> [destination.md]');
  const p = await api(`/posts/${id}?context=edit`);

  mkdirSync(CONTENT, { recursive: true });
  const file = dest ? resolve(dest) : join(CONTENT, `${p.slug || 'post-' + p.id}.md`);

  /* A pulled post is HTML. The file it would land on may be the Markdown this
     post was written from — same slug, same folder — and overwriting that
     would destroy the source to replace it with the rendered output, which is
     the one direction this conversion does not go back. */
  if (existsSync(file)) {
    const current = readFileSync(file, 'utf8');
    if (!/^format:\s*html\s*$/m.test(current)) {
      die(
        `${file} already exists and is not a pulled file — it looks like the Markdown source.\n` +
          `Pulling would overwrite it with HTML and lose the original.\n` +
          `If you meant to, pull somewhere else:  npm run blog pull ${id} some/other/path.md`
      );
    }
  }

  /* The body comes down as HTML and is written as HTML. Converting it back to
     Markdown would be a guess, and a lossy one — this file is for editing an
     existing post, not for pretending it was ever Markdown. New posts written
     from scratch here are Markdown and are converted on the way up. */
  writeFileSync(
    file,
    serialise(
      {
        wpId: p.id,
        title: p.title.raw,
        slug: p.slug,
        status: p.status,
        excerpt: p.excerpt.raw.replace(/\s+/g, ' ').trim(),
        format: 'html',
      },
      p.content.raw
    )
  );

  console.log(`→ ${file}`);
}

async function push(file, allowPublish) {
  if (!file) die('Usage: push <file.md> [--allow-publish]');
  const path = resolve(file);
  const { meta, body } = parse(readFileSync(path, 'utf8'));

  if (!meta.title) die('Front matter needs a title.');

  /* Two locks on publishing, and this is the second: the file has to ask for
     it AND the command line has to allow it. Anything else becomes a draft,
     including a file that says `publish` and was pushed without the flag. */
  let status = meta.status || 'draft';
  if (status === 'publish' && !allowPublish) {
    console.log('! file says status: publish, but --allow-publish was not given — pushing as a draft');
    status = 'draft';
  }

  const content =
    meta.format === 'html' ? body : toBlocks(marked.parse(body, { mangle: false, headerIds: false }));

  const payload = { title: meta.title, content, status };
  if (meta.slug) payload.slug = meta.slug;
  if (meta.excerpt) payload.excerpt = meta.excerpt;

  const existing = meta.wpId && Number(meta.wpId);
  const result = existing
    ? await api(`/posts/${existing}`, { method: 'POST', body: JSON.stringify(payload) })
    : await api('/posts', { method: 'POST', body: JSON.stringify(payload) });

  if (!existing) {
    /* Written back so the next push updates this post instead of creating a
       second copy of it. */
    writeFileSync(path, serialise({ wpId: result.id, ...meta }, body));
    console.log(`created #${result.id} · wpId written back to ${file}`);
  } else {
    console.log(`updated #${result.id}`);
  }

  console.log(`status: ${result.status}\n${result.link}`);
  if (result.status !== 'publish') {
    console.log('Draft — nothing is public until you publish it from wp-admin.');
  }
}

/**
 * Reads, and optionally sets, the blog's name and tagline.
 *
 * These are the two strings a fresh WordPress ships with placeholders for —
 * "My Blog" and "My WordPress Blog" — and they appear in the blog's header, in
 * its feed, and in the browser tab. Left alone they read as an unfinished site,
 * which is a poor first impression for a page the main site links to by name.
 */
async function site(title, description) {
  if (!title) {
    const s = await api('/settings');
    console.log(`title:       ${s.title}`);
    console.log(`description: ${s.description}`);
    console.log('\nTo change:  npm run blog site "New title" "New tagline"');
    return;
  }

  const payload = { title };
  if (description) payload.description = description;

  const s = await api('/settings', { method: 'POST', body: JSON.stringify(payload) });
  console.log(`title:       ${s.title}`);
  console.log(`description: ${s.description}`);
}

/**
 * Uploads an image and, given a post, makes it that post's featured image.
 *
 * The index is a grid of cards and a card without an image is a line of text
 * in a lot of white space — so this is not decoration, it is most of what the
 * landing page looks like.
 *
 * Uploads are a raw body with a filename in `Content-Disposition`, not JSON,
 * which is why this does not go through `api()`.
 */
async function cover(file, postId) {
  if (!file) die('Usage: cover <image> [postId]');

  const path = resolve(file);
  if (!existsSync(path)) die(`${path} not found.`);

  const bytes = readFileSync(path);
  const name = path.split(/[\\/]/).pop();
  const ext = name.split('.').pop().toLowerCase();
  const type = { jpg: 'image/jpeg', jpeg: 'image/jpeg', png: 'image/png', webp: 'image/webp' }[ext];
  if (!type) die(`${ext} is not an image type WordPress will take here (jpg, png, webp).`);

  const res = await fetch(`${API}/media`, {
    method: 'POST',
    headers: {
      Authorization: auth(),
      'Content-Type': type,
      'Content-Disposition': `attachment; filename="${name}"`,
    },
    body: bytes,
  });

  const media = await res.json();
  if (!res.ok) die(`upload → ${res.status}\n${media.message || ''}`);

  console.log(`uploaded #${media.id} · ${Math.round(bytes.length / 1024)} KB · ${media.source_url}`);

  if (postId) {
    await api(`/posts/${postId}`, { method: 'POST', body: JSON.stringify({ featured_media: media.id }) });
    console.log(`set as the featured image on #${postId}`);
  }
}

async function trash(id) {
  if (!id) die('Usage: trash <id>');
  /* No `force=true`. This moves the post to the WordPress trash, where it can
     be restored; emptying the bin is a decision for a person in wp-admin. */
  const r = await api(`/posts/${id}`, { method: 'DELETE' });
  console.log(`#${id} → ${r.status || 'trash'} (restorable from wp-admin)`);
}

/* ── Entry ───────────────────────────────────────────────────────────────── */

/**
 * Ends the run with a message and a non-zero status.
 *
 * Throws rather than calling `process.exit`. Exiting while a socket is still
 * open aborts Node on Windows with a libuv assertion, which buries the actual
 * explanation under a crash dump — and the explanation is the entire point of
 * this function.
 */
class Handled extends Error {}

function die(message) {
  console.error(message);
  process.exitCode = 1;
  throw new Handled(message);
}

const [command, arg, arg2] = process.argv.slice(2);
const allowPublish = process.argv.includes('--allow-publish');

const commands = {
  list: () => list(),
  pull: () => pull(arg, arg2),
  push: () => push(arg, allowPublish),
  trash: () => trash(arg),
  site: () => site(arg, arg2),
  cover: () => cover(arg, arg2),
};

if (!commands[command]) {
  die('Commands: list · pull <id> · push <file> [--allow-publish] · trash <id> · site [title] [tagline] · cover <image> [postId]');
}

try {
  await commands[command]();
} catch (e) {
  if (!(e instanceof Handled)) throw e;
}
